
export const videoData = [
    {
          "videoId": "video01", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/hQAHSlTtcmY/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "video01", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://static.skillshare.com/uploads/video/thumbnails/fe1809cd178d3a6432bffb5ae8104828/original",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "video01", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/c_ehAS66Q_Q/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "video01", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/JOa41r3Fr4s/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLD2q0JqQq2FtVrPRdkzD0DDhMrd5w",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "video01", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTe1fd-o3TUEb572k_EMh3FFpP95yQcEoLzMA&s",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "video01", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/s3Wx97keQys/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "video01", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/s3Wx97keQys/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "video01", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/s3Wx97keQys/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "video01", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/s3Wx97keQys/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "video01", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/s3Wx97keQys/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "video01", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/s3Wx97keQys/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    }
]