
export const videoData = [
    {
          "videoId": "1", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/hQAHSlTtcmY/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "category" :"javascript",
             "videoUrl":"https://www.youtube.com/embed/hQAHSlTtcmY",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "2", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://static.skillshare.com/uploads/video/thumbnails/fe1809cd178d3a6432bffb5ae8104828/original",
             "description": "A quick tutorial to get started with React.",
             "category" :"Web development",
              "videoUrl":"https://www.youtube.com/embed/c_ehAS66Q_Q",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200,               //c_ehAS66Q_Q
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "3", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/c_ehAS66Q_Q/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "category" :"data science",
             "videoUrl":"https://www.youtube.com/embed/c_ehAS66Q_Q",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "4", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/kiduOidrIZs/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDBrIEYWTOvoBYdYMMxqZM4W4gIRQ",
             "description": "A quick tutorial to get started with React.",
             "videoUrl":"https://www.youtube.com/embed/kiduOidrIZs",
             "category" :"music",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "5", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/9y9UEAkB2VA/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "category" :"podcasts",
             "videoUrl":"https://www.youtube.com/embed/9y9UEAkB2VA",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ]   // 
    },
    {
          "videoId": "6", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/sISz8MuSgRQ/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "category" :"show",
              "videoUrl":"https://www.youtube.com/embed/sISz8MuSgRQ",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "7", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/s3Wx97keQys/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "category" :"information technology",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "8", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/s3Wx97keQys/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "9", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/s3Wx97keQys/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "10", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/s3Wx97keQys/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    },
    {
          "videoId": "11", 
            "title": "Learn React in 30 Minutes", 
            "thumbnailUrl":"https://i.ytimg.com/vi/s3Wx97keQys/maxresdefault.jpg",
             "description": "A quick tutorial to get started with React.",
             "channelId": "channel01",
             "uploader": "user01", 
             "views": 15200, 
             "likes": 1023,
            "dislikes": 45, 
             "uploadDate": "2024-09-20",
             "comments": [ { "commentId": "comment01", 
                             "userId":"user02",
                              "text": "Great video! Very helpful.",
                               "timestamp": "2024-09-21T08:30:00Z" } ] 
    }
]